### ISSUE TITLE
Crash when I create a new bus line

### ISSUE THREAD

**Issue by xLecon** [klyte45/TransportLinesManager#146]
When I want to create a new bus line (I have not tried with other means of transport yet) it gives me crash, here is my log
[output_log.txt](https://github.com/klyte45/TransportLinesManager/files/7373743/output_log.txt)

#Bug

**Comment by xLecon** [comment]
> If you can, give a try in the current [alpha version](https://github.com/klyte45/TransportLinesManager/tree/alpha/_requiredDLLs) to check if the problem remains. Just copy this files in your local APPDATA Cities Skylines folder under path: `Addons/Mods/TLM`
> 
> I added some fixes related to this issue there.

The alpha version didn't fix the crash, I tried to create a new bus line and the game crashed. I don't know why SifVerT worked and it didn't work for me. I think I installed it fine, I did what you told me.

**Comment by avmantonio** [comment]
@klyte45 have you taken a look at the outlogs me and @CrankyAnt have uploaded? it's good to know the issue is solved for some people. but we still can´t

**Comment by SkillzGamingYT** [comment]
#143

**Comment by WILL07555** [comment]
Hi I have the alpha version and it still crashed the game until i paused the game first then added 3 bus routes which didn't crash the game and then i could make bus routes with the pause off, not sure why this happened but it was the way i could get past the crashes and it was only bus lines nothing else.

I hope this helps

**Comment by moonchildinthewild** [comment]
Hi,
Today I tried with the alpha version. On the first launch a pop-up notifyed me for updated TLM appeared, but the issue was still present. I also tried the workaround creating 3 bus lines when the game is paused, but than it crashes again, when I try to create new one. The issue is only for bus lines, not for other types of transport.
Here is my output_log file. I saved the game, then tried to create a bus line and than the game crashed. As I can see there is an exception in the end of the log.

[output_log.txt](https://github.com/klyte45/TransportLinesManager/files/7527916/output_log.txt)

**Comment by avmantonio** [comment]
@klyte45 I tried the method of @WILL07555  it worked for me, no crashing when creating bus Lunes. But then all the bus lines started reducing bus count to 0. Then passengers started ignoring bus stops and kept walking. Similar case reported before (I also migrated from IPT2 to this mod when that happened). I hope you found a fix to all this issues to use your mod continuously.

Also how do you even add more bus per line??  I felt so noobie and couldn't find where

**Comment by klyte45** [comment]
Well, I will close this issue to make all information concentrated in the #143, once the bug is the same. 
I explained next steps there.

@avmantonio you can add more buses by the budget screen - up to one value per hour or just one setting for all day. You can set directly the fixed amount by making the line use a specific setting for all settings (checkbox in bottom of line window checked). In 14.2 will be allowed to type the values directly instead of just being possible via the slider.
