### ISSUE TITLE
[BUG]Airport Express Train disappeared in TLM Assets List after using AVO

### ISSUE THREAD

**Issue by Awd1242** [klyte45/TransportLinesManager#265]
**Describe the bug**
Before using TLM, I use Advanced Vehicle Options(AVO) to disable the spawn of Airport Express Train. But when I re-set the AVO, the vehicle still disappeared in TLM assets list.I even create a new asset for Airport Express Train, but it was no use.
I have test other vehicles, all other vehicle can appear in TLM when set to spawn in AVO, expect Airport Express Train.

**Game Logs**
[output_log.txt](https://github.com/klyte45/TransportLinesManager/files/9028578/output_log.txt)

**Screenshots**
![Screenshots 2022-07-01 190609](https://user-images.githubusercontent.com/52704313/176888953-23ddba4f-24bf-457d-8baf-25b9b7fb35eb.jpg)
In this Screenshot, I manage to use Airport Express Train without TLM enabled. But in TLM it's still disappeared. 
![Screenshots 2022-07-01 195132](https://user-images.githubusercontent.com/52704313/176889814-7567fb1b-f134-40e6-b1a2-977010c26b4a.jpg)
In AVO List, I have set the vehicle to spawn, but it's no use in TLM, although this is my own created vehicle asset.

**Comment by Transportation-master-kcl** [comment]
I've got this bug too. Even if I unsubscribe to AVO, the Airport Express Train still doesn't show up.

**Comment by klyte45** [comment]
The enable/disable in TLM was solved in current version.
Version: v14.3.0 r2

**Comment by Awd1242** [comment]
> The enable/disable in TLM was solved in current version. Version: v14.3.0 r2

![屏幕截图 2022-09-17 124524](https://user-images.githubusercontent.com/52704313/190840890-eca2d89c-e89f-4150-989c-f92bc1e28b51.jpg)
I have tried to unsubscribe and re-subscribe both AVO and TLM to solve the problem, but the train still doesn't appear in TLM
![屏幕截图 2022-09-17 130319](https://user-images.githubusercontent.com/52704313/190841380-f7ff0994-14d4-43cc-a467-0743e2501b27.jpg)
Still, disable TLM and I can use Airport Express Train with vanilla Lines Overview. This time I use a brand new city to test.
So what should I do now? reinstall the whole game?

**Comment by Transportation-master-kcl** [comment]
The bug persists even reinstalling the whole game. I got the exact same bug for months already.
